### ISSUE TITLE
What is the purpose of this repo?

### ISSUE THREAD

**Issue by MeoMix** [jspm/nodelibs-fs#3]
Hey,

I was trying to get autoprefixer working with jspm 0.17

I was getting along decently well until I hit an error with `npm:browserslist@1.1.1`

It's throwing an error `fs.existsSync` because it's working on the assumption its running in node. It checks for the existence of `readFileSync` before attempting to use `fs.existsSync`... but that just happens to pass due to the existence of this library.

It looks like if `existsSync` and `statSync(..).isFile()` were implemented then it'd happily call `readFileSync`, but it's not clear to me whether that's even desired or if it should just exit.

EDIT: It looks like if I simply return false always from `existsSync` then we're in business.

**Comment by guybedford** [comment]
Yes this library is an incomplete browser fs implementation designed to support old cases of brfs via sync XHR. I'm open to a PR on existsSync or statSync that returns false or throws.

**Comment by MeoMix** [comment]
I ended up submitting a PR to browserslist to get them to check for the existence of existsSync and statSync before calling them. If this file isn't proving problematic for others than I don't see a need to build upon it for now. It was just a little surprising to have require('fs') return something, but not have that something be a full implementation.

**Comment by guybedford** [comment]
Sure, yes this file is certainly hanging on a thread here, PRs always welcome.
